use edit_ease;
DROP TABLE IF EXISTS images CASCADE;

CREATE TABLE images (
    pictureID INT PRIMARY KEY AUTO_INCREMENT,
    userID INT,
    fileName VARCHAR(255) NOT NULL,
    filePath VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES users(userID)
);